"""add_practice_test_table

Revision ID: 16c9a9b01f4c
Revises: e21b3d6cd509
Create Date: 2025-08-31 18:45:13.314227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16c9a9b01f4c'
down_revision = 'e21b3d6cd509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'practice_tests',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('test_date', sa.DateTime(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('question_id', sa.Integer(), nullable=False),
        sa.Column('grade_level', sa.String(length=50), nullable=False),
        sa.Column('status', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['question_id'], ['questions.id']),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_practice_tests_id'), 'practice_tests', ['id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_tests_id'), table_name='practice_tests')
    op.drop_table('practice_tests')
    # ### end Alembic commands ###
