"""add_test_identifier_to_practice_tests

Revision ID: a086e63da384
Revises: 4f98a147fac6
Create Date: 2025-08-31 18:57:10.698918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a086e63da384'
down_revision = '4f98a147fac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'practice_tests',
        sa.Column(
            'test_identifier',
            sa.String(length=50),
            nullable=False,
            server_default=''
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practice_tests', 'test_identifier')
    # ### end Alembic commands ###
